/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'root' at '12/12/17 11:08 AM' with Gradle 3.2.1
 *
 * @author root, @date 12/12/17 11:08 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return false;
    }
}
